version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      # SessionManager 플러그인 설치
      - echo "Installing AWS Session Manager Plugin..."
      - sudo yum install -y https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm
      - session-manager-plugin --version


      # SSH 키 및 Nginx 설정 다운로드
      - echo "Fetching secrets from Parameter Store..."

      - echo "Creating necessary directories..."
      - mkdir -p .platform/nginx
      - mkdir -p .ebextensions

      - aws ssm get-parameter --name "/platform_nginx_conf" --query "Parameter.Value" --output text > .platform/nginx/nginx.conf
      - if [ -s .platform/nginx/nginx.conf ]; then echo "nginx.conf downloaded successfully."; else echo "Failed to download nginx.conf."; exit 1; fi

      - aws ssm get-parameter --name "/ebextensions_nginx_config" --query "Parameter.Value" --output text > .ebextensions/nginx_config.config
      - if [ -s .ebextensions/nginx_config.config ]; then echo "nginx_config.config downloaded successfully."; else echo "Failed to download nginx_config.config."; exit 1; fi

      - aws ssm get-parameter --name "/Procfile" --query "Parameter.Value" --output text > Procfile
      - if [ -s Procfile ]; then echo "Procfile downloaded successfully."; else echo "Failed to download Procfile."; exit 1; fi

  pre_build:
    commands:
      - echo "Preparing for build..."
      - chmod +x ./gradlew
      # CodeBuild 환경 변수로부터 DB 정보 가져오기
      - export DB_HOST=$DB_HOST
      - export DB_PORT=$DB_PORT
      - export DB_USERNAME=$DB_USERNAME
      - export DB_PASSWORD=$DB_PASSWORD
      - export DB_NAME=$DB_NAME
      - export EC2_HOST=$EC2_HOST
      - export AWS_ACCESS_KEY=$AWS_ACCESS_KEY
      - export AWS_BUCKET=$AWS_BUCKET
      - export AWS_REGION=$AWS_REGION
      - export AWS_SECRET_KEY=$AWS_SECRET_KEY
      - export JWT_SECRET=$JWT_SECRET

      # SSH 터널링 설정
      - echo "Setting up SSH tunnel..."
      - aws ssm start-session --target $EC2_HOST --document-name AWS-StartPortForwardingSession --parameters '{"portNumber":["3306"],"localPortNumber":["3306"]}' & sleep 10  # 터널링 연결 대기

  build:
    commands:
      - echo "Building the application with Gradle..."
      - ./gradlew build -x test
      - echo "Renaming the built JAR file..."
      - mv build/libs/songyeoin-backend-0.0.1-SNAPSHOT.jar application.jar

  post_build:
    commands:
      - echo Build completed on `date`

      - echo "Checking if application.jar exists..."
      - if [ -f application.jar ]; then echo "application.jar found."; else echo "application.jar not found!"; exit 1; fi
      - if [ ! -f Procfile ]; then echo "Procfile missing!"; exit 1; fi
      - if [ ! -s .ebextensions/nginx_config.config ]; then echo "nginx_config.config missing!"; exit 1; fi
      - if [ ! -s .platform/nginx/nginx.conf ]; then echo "nginx.conf missing!"; exit 1; fi

      - echo "Contents of build/libs after copy:"
      - ls -R

artifacts:
  files:
    - application.jar
    - Procfile
    - .ebextensions/**   # Include all files under .ebextensions
    - .platform/**       # Include all files under .platform
  discard-paths: no                   # Preserve directory structure
