application:
  name: SongyeoinBackendApplication

server:
  port: 8080
  error:
    include-message: always
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE:songyeoin}?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:songyeoin}
    password: ${MYSQL_PASSWORD:songyeoin}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


management:
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    org.springframework: INFO
    com.ict: DEBUG

jwt:
  secret: "7ZWc7IOd7KCc7J6Q7Yq47Yq467Cx7Iuc7Yq4IO2VnOq1rOudvCDsoIDslYjsirXrs7Qg" # Base64 인코딩된 시크릿 키 (송여인스프링부트프로젝트)
  accessTokenValidity: 1800000 # Access Token 유효시간 (30분)
  refreshTokenValidity: 1209600000 # Refresh Token 유효시간 (14일)