application:
  name: SongyeoinBackendApplication

server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE:songyeoin}?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:songyeoin}
    password: ${MYSQL_PASSWORD:songyeoin}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


management:
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    org.springframework: INFO
    com.ict: DEBUG

jwt:
  secret: 7Iah7Jes7J247Iqk7ZSE66eB67aA7Yq47ZSE66Gc7KCd7Yq4
  validity: 3600000  # 유효 시간 (예: 1시간=3600000 밀리초)
  issuer: ${JWT_ISSUER:https://dev-carrot.sellease.io}/
  expirationMinute: 10